### PR TITLE
Close mobile menu on navigation end

### LINKED ISSUE #47: Menu does not close as expected on mobile route changes.
**Describe the bug**
Mobile menu does not close when navigating to a new shallow route (/about, etc)

**To Reproduce**

1. Go to any page on mobile
2. Click on the hamburger menu
3. Click any top-level button (like 'about')
4. Menu remains open after switching pages

**Expected behavior**
Menu closes on route change

### PR DESCRIPTION
**Pull request by AndrewLester**
## Status:
:rocket:
## Description
Closes the mobile menu on any navigation changes. I went for a more global solution since it more closely resembles the functionality of MPAs. If desired, I can alter the code to only close the mobile navigation when _nav menu_ links are clicked, but I do think that closing the menu on all navigation changes is more familiar to the user.

Fixes: #47 

## Videos

https://user-images.githubusercontent.com/23221268/144532184-0e57ca72-3825-41c2-bf47-a39907458ece.mov

### CODE REVIEW

File: src/components/Nav.svelte [hunk 1]
```diff
@@ -14,7 +14,10 @@
   let windowWidth: number | undefined;
 </script>
 
-<svelte:window bind:innerWidth={windowWidth} />
+<svelte:window
+  bind:innerWidth={windowWidth}
+  on:sveltekit:navigation-end={() => (showMobileMenu = false)}
+/>
```
Comment (SirajChokshi) [inline src/components/Nav.svelte:13]: Great work!

We can delete all the code in the comments above these lines now (it's within the scope of this PR)

```js
  // let oldSegment: string;

  let showMobileMenu = false;

  // $: {
  //   if (segment !== oldSegment || (path && !path.startsWith(segment))) {
  //     showMobileMenu = false;
  //   }
  // }
```

**Review by SirajChokshi — APPROVED** [review]
Looks good. This implementation behaves well :)
